---
- name: arrange
  set_fact:
    date: "{{ lookup('pipe', 'date -d \"\" +\"%Y-%m-%d\"') }}"

- name: arrange
  command: "{{ item.command }}"
  with_items:
    - command: "dojo new-workspace test"

- name: act
  command: "{{ item.command }}"
  args:
    chdir: "/home/project/{{ date }}-test"
  with_items:
    - command: "dojo init c"
    - command: "dojo build"
