---
- name: arrange
  set_fact:
    workspace_dir: "/home/project/{{ lookup('pipe', 'date -d \"\" +\"%Y-%m-%d\"') }}-test"

- name: arrange
  command: "{{ item.command }}"
  with_items:
    - command: "dojo new-workspace test"

- name: arrange
  command: "{{ item.command }}"
  args:
    chdir: "{{ workspace_dir }}"
  with_items:
    - command: "dojo init typescript"
    - command: "dojo build"
    - command: "dojo rebuild"

- name: arrange
  copy:
    content: ''
    dest: "{{ item.dest }}"
    mode: 0o666
  with_items:
    - dest: "{{ workspace_dir }}/coverage/.marker"

- name: act
  command: "{{ item.command }}"
  args:
    chdir: "{{ workspace_dir }}"
  with_items:
    - command: "dojo rebuild"
