dependency:
  name: galaxy
driver:
  name: docker
  provider:
    name: docker
lint:
  name: yamllint
platforms:
  - name: theia-ide-next-web-v1.15.0
    image: talsenteam/docker-applications:theia-ide-next-web-v1.15.0
    pull: false
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - lint
    - syntax
    - destroy
    - create
    - prepare
    - converge
    - verify
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
    options:
      ignore: 'E501'
